.Dd $Mdocdate: Sep 21 2024$
.Dt GENPASS 1
.Sh NAME
.Nm genpass
.Nd generate random passwords
.Sh SYNOPSIS
.Nm genpass
.Op Fl adsw
.Op Ar length
.Sh DESCRIPTION
The
.Nm
utility generates a random password of
.Ar length
characters, or 32 characters if
.Ar length
is not specified.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl a
include alphabetical characters in the output
.It Fl d
include digits in the output
.It Fl s
include ascii symbols in the output
.It Fl w
include whitespace in the output
.El
.Pp
If none of
.Fl adsw
are specified, a password including alphanumeric characters and 
symbols will be generated.
.Sh EXIT STATUS
.Ex -std
